### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ahmadiphy** [dawidkopczyk/speech_recognition#3]
I can't understand why this error occurred!?

Traceback (most recent call last):  
File "main.py", line 24, in <module>
    df = dsGen.load_data(DIR)
  File "./dataset.py", line 40, in load_data
    wav_files = [x.split(sep='\\')[1] + '/' + x.split(sep='\\')[2] for x in wav_files]
  File "./dataset.py", line 40, in <listcomp>
    wav_files = [x.split(sep='\\')[1] + '/' + x.split(sep='\\')[2] for x in wav_files]
IndexError: list index out of range

**Comment by ahmadiphy** [comment]
Problem Solved!
for Linux machine, the code should be edited as follow:
wav_files = [x.split(sep='/')[1] + '/' + x.split(sep='/')[2] for x in wav_files]
